ALTER TABLE processing_queue
  ADD COLUMN IF NOT EXISTS vat_amount NUMERIC(10,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS vat_rate   NUMERIC(4,2)  DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_duplicate_suspect BOOLEAN DEFAULT false;
